
export const CUSTOMERS_LOADING = 'CUSTOMERS_LOADING'
export const CUSTOMERS_FAILED = 'CUSTOMERS_FAILED'
export const CUSTOMERS_SUCCESS = 'CUSTOMERS_SUCCESS'
export const CUSTOMERS_GET = 'CUSTOMERS_GET'
// export const CUSTOMERS_GET_EDIT = 'CUSTOMERS_GET_EDIT'